<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diego Martínez">

<title>Trabajo 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="quarto_files/libs/quarto-html/quarto.js"></script>
<script src="quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="quarto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="quarto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#el-riesgo-politico-en-chile-y-sus-posibles-impacto-en-las-inversiones-extranjeras." id="toc-el-riesgo-politico-en-chile-y-sus-posibles-impacto-en-las-inversiones-extranjeras." class="nav-link active" data-scroll-target="#el-riesgo-politico-en-chile-y-sus-posibles-impacto-en-las-inversiones-extranjeras."><span class="header-section-number">1</span> <strong>El riesgo politico en Chile y sus posibles impacto en las inversiones extranjeras.</strong></a></li>
  <li><a href="#por-diego-martinez" id="toc-por-diego-martinez" class="nav-link" data-scroll-target="#por-diego-martinez"><span class="header-section-number">2</span> Por: Diego Martinez</a>
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">2.1</span> <strong>Introducción:</strong></a></li>
  <li><a href="#analisis-descriptivo-de-variables" id="toc-analisis-descriptivo-de-variables" class="nav-link" data-scroll-target="#analisis-descriptivo-de-variables"><span class="header-section-number">2.2</span> Analisis descriptivo de variables</a></li>
  </ul></li>
  <li><a href="#gráfico-de-inversión-extranjera-directa-para-los-paises-latinoamericanos." id="toc-gráfico-de-inversión-extranjera-directa-para-los-paises-latinoamericanos." class="nav-link" data-scroll-target="#gráfico-de-inversión-extranjera-directa-para-los-paises-latinoamericanos."><span class="header-section-number">3</span> gráfico de inversión extranjera directa para los paises latinoamericanos.</a>
  <ul class="collapse">
  <li><a href="#correlación-entre-variables" id="toc-correlación-entre-variables" class="nav-link" data-scroll-target="#correlación-entre-variables"><span class="header-section-number">3.1</span> correlación entre variables</a></li>
  </ul></li>
  <li><a href="#estimacion-de-regresiones." id="toc-estimacion-de-regresiones." class="nav-link" data-scroll-target="#estimacion-de-regresiones."><span class="header-section-number">4</span> Estimacion de regresiones.</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Diego Martínez </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="el-riesgo-politico-en-chile-y-sus-posibles-impacto-en-las-inversiones-extranjeras." class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> <strong>El riesgo politico en Chile y sus posibles impacto en las inversiones extranjeras.</strong></h1>
</section>
<section id="por-diego-martinez" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Por: Diego Martinez</h1>
<section id="introducción" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">2.1</span> <strong>Introducción:</strong></h2>
<p>Los trabajos sobre riesgo politico son propios de los profesionales de negocios internacionales (ver <span class="citation" data-cites="jeffreysimonTheoreticalPerspectivePolitical1984">Jeffrey Simon and Simon (<a href="#ref-jeffreysimonTheoreticalPerspectivePolitical1984" role="doc-biblioref">1984</a>)</span>), sin embargo es posible encontrar trabajos que aborden el riesgo politico desde la ciencia política este es el caso del estudio de Johannes Leitner que define al riesgo político como “un concepto que cubre aquellos factores de riesgo para las empresas internacionales que están arraigados en el entorno político e institucional de un país pero que tienen consecuencias inmediatas en el desempeño de la empresa”.<span class="citation" data-cites="johannesleitnerPoliticalRisksPostSoviet2016">(ver <a href="#ref-johannesleitnerPoliticalRisksPostSoviet2016" role="doc-biblioref">Johannes Leitner and H. Meissner 2016</a>)</span></p>
<p>Ahora bien existen pocos trabajos desde la ciencia política que vean la relación entre los regimenes politicos y los distintos tipos de riesgo politicos que existen, por lo que, el objetivo de este trabajo sera ver la relacion existente entre la estabilidad política y el riesgo politico, con la finalidad de ver el impacto que tienen ambos en la inversion extranjera. cabe destacar que los tipos de riesgos politicos no se evaluaran en base a la perspectiva del inversionista, sino mas bien, en la percepcion de la ciudadania con respecto al regimen politico en el que estan inmersos para ver asi como estas percepciones podrian afectar la estabilidad del regimen y en consecuencia al marco juridico de las inversiones en Chile.</p>
<p>Es debido a lo anterior que este trabajo se enmarcara dentro del estudio de la politica comparada (<span class="citation" data-cites="pasquino2014">Pasquino (<a href="#ref-pasquino2014" role="doc-biblioref">2014</a>)</span>) , pues se pretende comparar la estabilidad de distintos regimenes de latinoamerica con la finalidad de explorar como es el clima politico para los negocios ,asi como, posibles percepciones que podrian derivar en conflictos politicos internos que amenacen tanto al regimen como las empresas.</p>
<p>algunas factores que se consideran dentro de la categoria de riesgo politico, y que afectan a Chile son: la corrupción, crimen organizado, el clima de negocios (esto segun el ultimo informe de riesgo politico en America Latina).</p>
<p>ademas dentro del riesgo político encontramos los siguientes indicadores del riesgo: expectativas económicas vs.&nbsp;realidad; fracasos de la planificación económica; dirección política; conflicto externo; corrupción en el gobierno; injerencia del ejército en política; influencia de la religión organizada en política; ley y tradición de orden; tensiones raciales y de nacionalidad; terrorismo político; guerra civil; desarrollo de partidos políticos; y calidad de la burocracia. (Loyola, 2006)</p>
<p>En el presente trabajo se realizara un analisis de caracter exploratorio con la finalidad de responder a la pregunta: ¿existe relacion entre las perspectivas politico-economicas y la cantidad de inversion extranjera directa? las variables a utilizar serán la percepción ciudadana con respecto al funcionamiento de la economia del pais, perspectuvas del regimen politico, percepción de la corrupción, variables sobre la percepcion de los derechos politicos y finalmente variables de conflicto social como: grado de acuerdo con las protestas, protección del Estado contra el crimen y la proteccion a la propiedad privada .</p>
<p>Como evidencia que apoya a este trabajo tenemos la investigación de Alejandro Astudillos quien demestra mediante un estudio cuantitativo que las instituciones politicas fuertes tienen un impacto positivo en el crecimiento economico asi como el clima de negocios y de las inversiones.<span class="citation" data-cites="AstudilloJimenezAlejandro">(ver <a href="#ref-AstudilloJimenezAlejandro" role="doc-biblioref">Jimenez, n.d.</a>)</span> Es por ello que en el presente trabajo se evaluara la percepcion de la ciudadania chilena, con la finalidad de detectar posibles riesgos para el clima de las inversiones y del sistema politico, para ello se recurrira a la base de datos de latinobarometro 2023 que es una encuesta que mide percepciones, actitudes y valores; mientras que para analizar el fujo de inversion extranjera se recurrira a las bases de datos que proporciona la CEPAL en su sitio web CEPALSTAT que entrega la cantidad de inversión extranjera directa medida en millones de dolares.</p>
</section>
<section id="analisis-descriptivo-de-variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="analisis-descriptivo-de-variables"><span class="header-section-number">2.2</span> Analisis descriptivo de variables</h2>
<p>En el presente trabajo las variables a utilizar son las siguientes:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">fun_econ</td>
<td style="text-align: left;">fun_econ</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.162725</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">econ_act</td>
<td style="text-align: left;">econ_act</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.461826</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">fun_demo</td>
<td style="text-align: left;">fun_demo</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.883308</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">gob_nodemo</td>
<td style="text-align: left;">gob_nodemo</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.461976</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">econ_act_anipas</td>
<td style="text-align: left;">econ_act_anipas</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.446407</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: left;">percep_corrup</td>
<td style="text-align: left;">percep_corrup</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.956063</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">conf_gob</td>
<td style="text-align: left;">conf_gob</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.000299</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">conf_cong</td>
<td style="text-align: left;">conf_cong</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.077021</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">conf_banc</td>
<td style="text-align: left;">conf_banc</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.553219</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">con_judicial</td>
<td style="text-align: left;">con_judicial</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.962949</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">desem_gob</td>
<td style="text-align: left;">desem_gob</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.597380</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: left;">prot_privada</td>
<td style="text-align: left;">prot_privada</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.486826</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: left;">prot_crimen</td>
<td style="text-align: left;">prot_crimen</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.977470</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: left;">imagen_prog_pais</td>
<td style="text-align: left;">imagen_prog_pais</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.031811</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">grad_protesta</td>
<td style="text-align: left;">grad_protesta</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.395284</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">apoyo_gob_militar</td>
<td style="text-align: left;">apoyo_gob_militar</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.624102</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">inv_ext_dir</td>
<td style="text-align: left;">inv_ext_dir</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10483.793158</td>
<td style="text-align: left;">53990.87 (-100.91-53889.96)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>como podemos ver las variables a utilizar son 17 donde encontramos variables de confianza en las instituciones politicas nacionales, como lo son: Gobierno, Congreso, poder judicial y finalmente en las instituciones bancarias. Por otro lado, tenemos variables de perspectivas economicas, entre las que destacan: satisfacción con el funcionamiento de la economia, imagen progreso país, economia con respecto al año pasado, percepcion economica actual.Tambien se utilizaran variables de satisfaccion con el regimen politico: satisfaccion con el funcionamientos de la democracia, acuerdo o desacuerdo ante un hipotetico gobierno no democratico, apoyo a un golpe militar o no, ademas de una variable sobre el desempeño del gobiero. Por ultimo, encontramos variables de derechos politicos como son: grado de acuerdo con las protestas, protección del Estado contra el crimen y protección a la propiedad privada.</p>
</section>
</section>
<section id="gráfico-de-inversión-extranjera-directa-para-los-paises-latinoamericanos." class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> gráfico de inversión extranjera directa para los paises latinoamericanos.</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>en el presente grafico podemos ver los paises y sus la respectiva inversión extranjera que reciben, siendo Brasil el pais que mayor inversion extranjera recibe y el Salvador el que menos recibe.</p>
<p>Ahora bien, con la finalidad de explicar la variación en la inversion extranjera de estos paises se juntaran las variables mas arriba seleccionadas para comprobar si la hipotesis: las variables politico-economicas afectan a la inversión extranjera.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">confianza_inst</td>
<td style="text-align: left;">confianza_inst</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.898372</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">percepcion_econ</td>
<td style="text-align: left;">percepcion_econ</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.454117</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">conflic_social</td>
<td style="text-align: left;">conflic_social</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.428630</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">estado_derecho</td>
<td style="text-align: left;">estado_derecho</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.732148</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">imagen_progreso_pais</td>
<td style="text-align: left;">imagen_progreso_pais</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.031811</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">corrupcion</td>
<td style="text-align: left;">corrupcion</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.956063</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">desempeño_gobierno</td>
<td style="text-align: left;">desempeño_gobierno</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.597380</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">inestabilidad_reg</td>
<td style="text-align: left;">inestabilidad_reg</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.624102</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">percepcion_politico_econ</td>
<td style="text-align: left;">percepcion_politico_econ</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.023017</td>
<td style="text-align: left;">3 (1-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">inv_ext_dir</td>
<td style="text-align: left;">inv_ext_dir</td>
<td style="text-align: right;">13360</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10483.793158</td>
<td style="text-align: left;">53990.87 (-100.91-53889.96)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como podemos observar las variables seleccionadas fueron agrupadas y promediadas en nueve dimensiones que permitan explicar la inversion extranjera, la primera de ellas es la confianza en las instituciones, la segunda es la percepcion economica, la tercera el conflicto social, la cuarta el Estado de derecho, la quinta la imagen progreso del pais, la sexta la corrupción, la septima el desempeño del gobierno la octava, la inestabilidad del regimen politico y finalmente la percepcion politico economica del país. cabe destacar que dichas variables fueron agrupadas segun las caracteristicas de las mismas, es decir, las categoricas con las categoricas y las binarias con sus respectivas variables es en base a la agrupación anterior que se lograron obtener las siguientes correlaciones.</p>
<section id="correlación-entre-variables" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="correlación-entre-variables"><span class="header-section-number">3.1</span> correlación entre variables</h2>
<p>Ahora bien, para analizar el impacto que tienen las variables seleccionadas en la inversión extranjera se utilizara la base de datos de Latinobarometro 2023 y los flujos de inversion extranjera neta segun datos de la cepalstats que tiene datos desde 1980 sobre el flujo de de las inversiones extranjeras en los paises latinoamericanos, sin embargo, por limitaciones de ambas bases de datos se excluyen los casos de Venezuela y Nicaragua el primero debido a que desde 2018 no cuenta con mas datos sobre su inversión extranjera directa, el segundo debido a que no participo de las encuestas de latinobarometro 2022, por lo que no aparece en la base de datos trabajada.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>como podemos ver existe una correlación bastante fuerte entre la percepción politico economica y la confianza en las instituciones.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En la presente matriz de correlaciones es posible observar que el coeficiente de correlación de Pearson entre la satisfacción con el funcionamiento de la economia y la satisfacción con el funcionamiento de la democracia es positivo y grande (r &gt;= 5) según Cohen (1988). Lo mismo ocurre con la satisfacción con la economia del año actual con respecto al año pasado.</p>
<p>sin embargo, las variables seleccionadas no son capaces de explicar la inversión extenjera directa.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Your package installed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pacman::p_load(sjlabelled, dplyr, stargazer, sjmisc, summarytools, : Failed to install/load:</code></pre>
</div>
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En el presente grafico podemos ver la correlación entre las distintas variables y sus grados de significancia, sin embargo, no encontramos relaciones entre las variables que nos permitan hablar de un impacto significativo en la inversion extranjera, la unica variable que afecta a la inversion extranjera pero de forma poco significativa es la evaluación del desempeño del gobierno, donde esta ultima explica en un 12% la caida de la inversion extranjera directa de los paises.</p>
</section>
</section>
<section id="estimacion-de-regresiones." class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Estimacion de regresiones.</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Aqui podemos ver las variables con mayor correlación y encontramos que la percepcion politico economica y la confianza tienen correlaciones fuertes, mientras que para la variable que buscamos explicar “la inversión extranjera” la unica variable con una correlacion, aunque bastante debil es desempeño del gobierno. a continiacion crearemos regreciones lineales con ambas variables para ver si es posible crear un modelo de regresión lineal capaz de explicar la relacion entre las variables seleccionadas.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="quarto_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A continuación podemos ver dos modelos de regresión y sus respectivas asociaciones, para el caso del desempeño de los gobiernos de turno y la cantidad de inversión extranjera vemos una asociacion negativa. mientras que en el segundo modelo presentado vemos que la asociacion entre la percepción politica economica y la confianza institucional es positiva.</p>
<p>a continuación se presentan los respectivos modelos de regresión lineal y sus interpretaciones:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;inversión extranjera directa&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 1&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Intercepto&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;16370.44&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(419.31)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;desempeño gobierno&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-3685.19&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(250.94)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.02&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.02&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;13360&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="2"&gt;*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>Empezamos por el primer modelo de regresión lineal en el que relacionamos la variable de desempeño del gobierno y su impacto en la inversión, es decir, el desempeño del gobierno en este modelo actua como predictor de la inversión extranjera. Este modelo tiene un coeficiente de regresión de -3685 lo que quiere decir que por cada unidad que aumente el desempeño del gobierno, la inversion extranjera decaera en 3685 millones de dolares. por otro lado el intercepto quiere decir que cuando el desempeño es cero o digamos no se toma en cuenta la inversion extranjera tendría un valor de 16370.44 millones de dolares, ahora bien este modelo segun el R2solo logra explicar 2% de la varianza de la variable dependiente(inversión extranjera) por lo que no es muy significativo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;confianza institucional&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 2&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Intercepto&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1.44&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.02)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;percepcion politico economica&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.48&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.01)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.27&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.27&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;13360&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="2"&gt;*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>En este segundo modelo de regresión lineal las variables a asociar son la percepción politico economica con la confianza institucional, en donde encontramos que nuestro predictor es la percepcion politico economica. a partir del modelo anteriormente expuesto podemos concluir: que el coeficiente de regresión es 0.48, lo que quiere decir que, por cada unidad que aumenta la percepción politico economica, la confianza institucional aumentara en un 0.48%. ahora bien en cuanto al R2 este nos dice que este modelo logra explicar un 27% de la varianza de la variable dependiente(confianza institucional).</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-jeffreysimonTheoreticalPerspectivePolitical1984" class="csl-entry" role="listitem">
Jeffrey Simon, and Jeffrey D. Simon. 1984. <span>“A <span>Theoretical Perspective</span> on <span>Political Risk</span>.”</span> <em>Journal of International Business Studies</em> 15 (3): 123–43. <a href="https://doi.org/10.1057/palgrave.jibs.8490499">https://doi.org/10.1057/palgrave.jibs.8490499</a>.
</div>
<div id="ref-AstudilloJimenezAlejandro" class="csl-entry" role="listitem">
Jimenez, Alejandro. n.d. <span>“Astudillo <span class="nocase">Jim<span class="nocase">é</span>nez</span>, <span>Alejandro</span>. (2017). <span>Flujos</span> de <span class="nocase">Inversi<span class="nocase">ó</span>n Directa</span>, <span class="nocase">Fortalecimiento Democr<span class="nocase">á</span>tico</span> y <span class="nocase">Coyuntura Pol<span class="nocase">í</span>tica</span>: <span>El Caso</span> de <span>Chile</span>. <span class="nocase">M<span class="nocase">é</span>xico</span> y <span class="nocase">La Cuenca Del Pac<span class="nocase">í</span>fico</span>, 6(18), 37-63. <span>Recuperado En</span> 19 de <span>Abril</span> de 2024, de <span class="nocase">http://www.scielo.org.mx/scielo.php?script=sci_arttext&amp;pid=S2007-53082017000300037&amp;lng=es&amp;tlng=es</span>.”</span>
</div>
<div id="ref-johannesleitnerPoliticalRisksPostSoviet2016" class="csl-entry" role="listitem">
Johannes Leitner, and H. Meissner. 2016. <span>“Political <span>Risks</span> in <span>Post-Soviet Markets</span> . <span>A Theoretical Approach</span> . 105-<span>Risks</span> in <span>International Business</span> . <span>Considering</span> the Market , While Not Neglecting the Political Dimension.”</span>
</div>
<div id="ref-pasquino2014" class="csl-entry" role="listitem">
Pasquino, Gianfranco. 2014. <em>Nuevo Curso de Ciencia Política</em>. Fondo de Cultura Económica.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>